/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package cgl.iotcloud.core.api.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings("all") public class TSensorDeployResponse implements org.apache.thrift.TBase<TSensorDeployResponse, TSensorDeployResponse._Fields>, java.io.Serializable, Cloneable, Comparable<TSensorDeployResponse> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TSensorDeployResponse");

  private static final org.apache.thrift.protocol.TField DEPLOYED_SITES_FIELD_DESC = new org.apache.thrift.protocol.TField("deployedSites", org.apache.thrift.protocol.TType.LIST, (short)1);
  private static final org.apache.thrift.protocol.TField RESPONSE_FIELD_DESC = new org.apache.thrift.protocol.TField("response", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TSensorDeployResponseStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TSensorDeployResponseTupleSchemeFactory());
  }

  public List<String> deployedSites; // optional
  public TResponse response; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  @SuppressWarnings("all") public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    DEPLOYED_SITES((short)1, "deployedSites"),
    RESPONSE((short)2, "response");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // DEPLOYED_SITES
          return DEPLOYED_SITES;
        case 2: // RESPONSE
          return RESPONSE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private _Fields optionals[] = {_Fields.DEPLOYED_SITES};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.DEPLOYED_SITES, new org.apache.thrift.meta_data.FieldMetaData("deployedSites", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.RESPONSE, new org.apache.thrift.meta_data.FieldMetaData("response", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TResponse.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TSensorDeployResponse.class, metaDataMap);
  }

  public TSensorDeployResponse() {
  }

  public TSensorDeployResponse(
    TResponse response)
  {
    this();
    this.response = response;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TSensorDeployResponse(TSensorDeployResponse other) {
    if (other.isSetDeployedSites()) {
      List<String> __this__deployedSites = new ArrayList<String>(other.deployedSites);
      this.deployedSites = __this__deployedSites;
    }
    if (other.isSetResponse()) {
      this.response = new TResponse(other.response);
    }
  }

  public TSensorDeployResponse deepCopy() {
    return new TSensorDeployResponse(this);
  }

  @Override
  public void clear() {
    this.deployedSites = null;
    this.response = null;
  }

  public int getDeployedSitesSize() {
    return (this.deployedSites == null) ? 0 : this.deployedSites.size();
  }

  public java.util.Iterator<String> getDeployedSitesIterator() {
    return (this.deployedSites == null) ? null : this.deployedSites.iterator();
  }

  public void addToDeployedSites(String elem) {
    if (this.deployedSites == null) {
      this.deployedSites = new ArrayList<String>();
    }
    this.deployedSites.add(elem);
  }

  public List<String> getDeployedSites() {
    return this.deployedSites;
  }

  public TSensorDeployResponse setDeployedSites(List<String> deployedSites) {
    this.deployedSites = deployedSites;
    return this;
  }

  public void unsetDeployedSites() {
    this.deployedSites = null;
  }

  /** Returns true if field deployedSites is set (has been assigned a value) and false otherwise */
  public boolean isSetDeployedSites() {
    return this.deployedSites != null;
  }

  public void setDeployedSitesIsSet(boolean value) {
    if (!value) {
      this.deployedSites = null;
    }
  }

  public TResponse getResponse() {
    return this.response;
  }

  public TSensorDeployResponse setResponse(TResponse response) {
    this.response = response;
    return this;
  }

  public void unsetResponse() {
    this.response = null;
  }

  /** Returns true if field response is set (has been assigned a value) and false otherwise */
  public boolean isSetResponse() {
    return this.response != null;
  }

  public void setResponseIsSet(boolean value) {
    if (!value) {
      this.response = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case DEPLOYED_SITES:
      if (value == null) {
        unsetDeployedSites();
      } else {
        setDeployedSites((List<String>)value);
      }
      break;

    case RESPONSE:
      if (value == null) {
        unsetResponse();
      } else {
        setResponse((TResponse)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case DEPLOYED_SITES:
      return getDeployedSites();

    case RESPONSE:
      return getResponse();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case DEPLOYED_SITES:
      return isSetDeployedSites();
    case RESPONSE:
      return isSetResponse();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TSensorDeployResponse)
      return this.equals((TSensorDeployResponse)that);
    return false;
  }

  public boolean equals(TSensorDeployResponse that) {
    if (that == null)
      return false;

    boolean this_present_deployedSites = true && this.isSetDeployedSites();
    boolean that_present_deployedSites = true && that.isSetDeployedSites();
    if (this_present_deployedSites || that_present_deployedSites) {
      if (!(this_present_deployedSites && that_present_deployedSites))
        return false;
      if (!this.deployedSites.equals(that.deployedSites))
        return false;
    }

    boolean this_present_response = true && this.isSetResponse();
    boolean that_present_response = true && that.isSetResponse();
    if (this_present_response || that_present_response) {
      if (!(this_present_response && that_present_response))
        return false;
      if (!this.response.equals(that.response))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(TSensorDeployResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetDeployedSites()).compareTo(other.isSetDeployedSites());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDeployedSites()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.deployedSites, other.deployedSites);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetResponse()).compareTo(other.isSetResponse());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetResponse()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.response, other.response);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TSensorDeployResponse(");
    boolean first = true;

    if (isSetDeployedSites()) {
      sb.append("deployedSites:");
      if (this.deployedSites == null) {
        sb.append("null");
      } else {
        sb.append(this.deployedSites);
      }
      first = false;
    }
    if (!first) sb.append(", ");
    sb.append("response:");
    if (this.response == null) {
      sb.append("null");
    } else {
      sb.append(this.response);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (response == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'response' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
    if (response != null) {
      response.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TSensorDeployResponseStandardSchemeFactory implements SchemeFactory {
    public TSensorDeployResponseStandardScheme getScheme() {
      return new TSensorDeployResponseStandardScheme();
    }
  }

  private static class TSensorDeployResponseStandardScheme extends StandardScheme<TSensorDeployResponse> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TSensorDeployResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // DEPLOYED_SITES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list46 = iprot.readListBegin();
                struct.deployedSites = new ArrayList<String>(_list46.size);
                for (int _i47 = 0; _i47 < _list46.size; ++_i47)
                {
                  String _elem48;
                  _elem48 = iprot.readString();
                  struct.deployedSites.add(_elem48);
                }
                iprot.readListEnd();
              }
              struct.setDeployedSitesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // RESPONSE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.response = new TResponse();
              struct.response.read(iprot);
              struct.setResponseIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TSensorDeployResponse struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.deployedSites != null) {
        if (struct.isSetDeployedSites()) {
          oprot.writeFieldBegin(DEPLOYED_SITES_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.deployedSites.size()));
            for (String _iter49 : struct.deployedSites)
            {
              oprot.writeString(_iter49);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.response != null) {
        oprot.writeFieldBegin(RESPONSE_FIELD_DESC);
        struct.response.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TSensorDeployResponseTupleSchemeFactory implements SchemeFactory {
    public TSensorDeployResponseTupleScheme getScheme() {
      return new TSensorDeployResponseTupleScheme();
    }
  }

  private static class TSensorDeployResponseTupleScheme extends TupleScheme<TSensorDeployResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TSensorDeployResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      struct.response.write(oprot);
      BitSet optionals = new BitSet();
      if (struct.isSetDeployedSites()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetDeployedSites()) {
        {
          oprot.writeI32(struct.deployedSites.size());
          for (String _iter50 : struct.deployedSites)
          {
            oprot.writeString(_iter50);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TSensorDeployResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.response = new TResponse();
      struct.response.read(iprot);
      struct.setResponseIsSet(true);
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list51 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.deployedSites = new ArrayList<String>(_list51.size);
          for (int _i52 = 0; _i52 < _list51.size; ++_i52)
          {
            String _elem53;
            _elem53 = iprot.readString();
            struct.deployedSites.add(_elem53);
          }
        }
        struct.setDeployedSitesIsSet(true);
      }
    }
  }

}

