/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package cgl.iotcloud.core.master.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings("all") public class THeartBeatResponse implements org.apache.thrift.TBase<THeartBeatResponse, THeartBeatResponse._Fields>, java.io.Serializable, Cloneable, Comparable<THeartBeatResponse> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("THeartBeatResponse");

  private static final org.apache.thrift.protocol.TField TOTAL_SENSORS_FIELD_DESC = new org.apache.thrift.protocol.TField("totalSensors", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField RESPONSIVE_SONSOR_FIELD_DESC = new org.apache.thrift.protocol.TField("responsiveSonsor", org.apache.thrift.protocol.TType.I32, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new THeartBeatResponseStandardSchemeFactory());
    schemes.put(TupleScheme.class, new THeartBeatResponseTupleSchemeFactory());
  }

  public int totalSensors; // required
  public int responsiveSonsor; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  @SuppressWarnings("all") public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TOTAL_SENSORS((short)1, "totalSensors"),
    RESPONSIVE_SONSOR((short)2, "responsiveSonsor");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TOTAL_SENSORS
          return TOTAL_SENSORS;
        case 2: // RESPONSIVE_SONSOR
          return RESPONSIVE_SONSOR;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __TOTALSENSORS_ISSET_ID = 0;
  private static final int __RESPONSIVESONSOR_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TOTAL_SENSORS, new org.apache.thrift.meta_data.FieldMetaData("totalSensors", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.RESPONSIVE_SONSOR, new org.apache.thrift.meta_data.FieldMetaData("responsiveSonsor", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(THeartBeatResponse.class, metaDataMap);
  }

  public THeartBeatResponse() {
  }

  public THeartBeatResponse(
    int totalSensors,
    int responsiveSonsor)
  {
    this();
    this.totalSensors = totalSensors;
    setTotalSensorsIsSet(true);
    this.responsiveSonsor = responsiveSonsor;
    setResponsiveSonsorIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public THeartBeatResponse(THeartBeatResponse other) {
    __isset_bitfield = other.__isset_bitfield;
    this.totalSensors = other.totalSensors;
    this.responsiveSonsor = other.responsiveSonsor;
  }

  public THeartBeatResponse deepCopy() {
    return new THeartBeatResponse(this);
  }

  @Override
  public void clear() {
    setTotalSensorsIsSet(false);
    this.totalSensors = 0;
    setResponsiveSonsorIsSet(false);
    this.responsiveSonsor = 0;
  }

  public int getTotalSensors() {
    return this.totalSensors;
  }

  public THeartBeatResponse setTotalSensors(int totalSensors) {
    this.totalSensors = totalSensors;
    setTotalSensorsIsSet(true);
    return this;
  }

  public void unsetTotalSensors() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __TOTALSENSORS_ISSET_ID);
  }

  /** Returns true if field totalSensors is set (has been assigned a value) and false otherwise */
  public boolean isSetTotalSensors() {
    return EncodingUtils.testBit(__isset_bitfield, __TOTALSENSORS_ISSET_ID);
  }

  public void setTotalSensorsIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __TOTALSENSORS_ISSET_ID, value);
  }

  public int getResponsiveSonsor() {
    return this.responsiveSonsor;
  }

  public THeartBeatResponse setResponsiveSonsor(int responsiveSonsor) {
    this.responsiveSonsor = responsiveSonsor;
    setResponsiveSonsorIsSet(true);
    return this;
  }

  public void unsetResponsiveSonsor() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __RESPONSIVESONSOR_ISSET_ID);
  }

  /** Returns true if field responsiveSonsor is set (has been assigned a value) and false otherwise */
  public boolean isSetResponsiveSonsor() {
    return EncodingUtils.testBit(__isset_bitfield, __RESPONSIVESONSOR_ISSET_ID);
  }

  public void setResponsiveSonsorIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __RESPONSIVESONSOR_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case TOTAL_SENSORS:
      if (value == null) {
        unsetTotalSensors();
      } else {
        setTotalSensors((Integer)value);
      }
      break;

    case RESPONSIVE_SONSOR:
      if (value == null) {
        unsetResponsiveSonsor();
      } else {
        setResponsiveSonsor((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case TOTAL_SENSORS:
      return Integer.valueOf(getTotalSensors());

    case RESPONSIVE_SONSOR:
      return Integer.valueOf(getResponsiveSonsor());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case TOTAL_SENSORS:
      return isSetTotalSensors();
    case RESPONSIVE_SONSOR:
      return isSetResponsiveSonsor();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof THeartBeatResponse)
      return this.equals((THeartBeatResponse)that);
    return false;
  }

  public boolean equals(THeartBeatResponse that) {
    if (that == null)
      return false;

    boolean this_present_totalSensors = true;
    boolean that_present_totalSensors = true;
    if (this_present_totalSensors || that_present_totalSensors) {
      if (!(this_present_totalSensors && that_present_totalSensors))
        return false;
      if (this.totalSensors != that.totalSensors)
        return false;
    }

    boolean this_present_responsiveSonsor = true;
    boolean that_present_responsiveSonsor = true;
    if (this_present_responsiveSonsor || that_present_responsiveSonsor) {
      if (!(this_present_responsiveSonsor && that_present_responsiveSonsor))
        return false;
      if (this.responsiveSonsor != that.responsiveSonsor)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(THeartBeatResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetTotalSensors()).compareTo(other.isSetTotalSensors());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTotalSensors()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.totalSensors, other.totalSensors);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetResponsiveSonsor()).compareTo(other.isSetResponsiveSonsor());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetResponsiveSonsor()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.responsiveSonsor, other.responsiveSonsor);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("THeartBeatResponse(");
    boolean first = true;

    sb.append("totalSensors:");
    sb.append(this.totalSensors);
    first = false;
    if (!first) sb.append(", ");
    sb.append("responsiveSonsor:");
    sb.append(this.responsiveSonsor);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class THeartBeatResponseStandardSchemeFactory implements SchemeFactory {
    public THeartBeatResponseStandardScheme getScheme() {
      return new THeartBeatResponseStandardScheme();
    }
  }

  private static class THeartBeatResponseStandardScheme extends StandardScheme<THeartBeatResponse> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, THeartBeatResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TOTAL_SENSORS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.totalSensors = iprot.readI32();
              struct.setTotalSensorsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // RESPONSIVE_SONSOR
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.responsiveSonsor = iprot.readI32();
              struct.setResponsiveSonsorIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, THeartBeatResponse struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(TOTAL_SENSORS_FIELD_DESC);
      oprot.writeI32(struct.totalSensors);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(RESPONSIVE_SONSOR_FIELD_DESC);
      oprot.writeI32(struct.responsiveSonsor);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class THeartBeatResponseTupleSchemeFactory implements SchemeFactory {
    public THeartBeatResponseTupleScheme getScheme() {
      return new THeartBeatResponseTupleScheme();
    }
  }

  private static class THeartBeatResponseTupleScheme extends TupleScheme<THeartBeatResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, THeartBeatResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetTotalSensors()) {
        optionals.set(0);
      }
      if (struct.isSetResponsiveSonsor()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetTotalSensors()) {
        oprot.writeI32(struct.totalSensors);
      }
      if (struct.isSetResponsiveSonsor()) {
        oprot.writeI32(struct.responsiveSonsor);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, THeartBeatResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.totalSensors = iprot.readI32();
        struct.setTotalSensorsIsSet(true);
      }
      if (incoming.get(1)) {
        struct.responsiveSonsor = iprot.readI32();
        struct.setResponsiveSonsorIsSet(true);
      }
    }
  }

}

